#application: ryanrockers
#version: 1
runtime: python37
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico     

- url: /apple-touch-icon\.png
  static_files: apple-touch-icon.png
  upload: apple-touch-icon\.png   

- url: /apple-touch-icon-precomposed\.png
  static_files: apple-touch-icon-precomposed.png
  upload: apple-touch-icon-precomposed\.png 

- url: /google07e132c4c2bd7028\.html  
  static_files: google07e132c4c2bd7028.html
  upload: google07e132c4c2bd7028\.html

- url: /BingSiteAuth\.xml  
  static_files: BingSiteAuth.xml
  upload: BingSiteAuth\.xml
  
- url: /sitemap\.xml  
  static_files: sitemap.xml
  upload: sitemap\.xml
  
- url: /robots\.txt  
  static_files: robots.txt
  upload: robots\.txt  
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /animation
  static_dir: animation

- url: /games
  static_dir: games  

- url: /images
  static_dir: images    
  
- url: /.*
  script: main.app
  secure: always
  redirect_http_response_code: 301

libraries:
- name: webapp2
  version: latest
  
- name: PIL
  version: "1.1.7"
